import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Inter } from 'next/font/google';
import {FloatingNav} from "@/components/FloatingNav";
import React from "react";
import { redirect } from 'next/navigation';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const navItems = [
        {
            name: "About",
            link: "/about",

        },
        {
            name: "Jobs",
            link: "/jobs",

        },
        {
            name: "Apprenticeships",
            link: "/apprenticeships",
        },
    ];

    return (

    <html lang="en" className={inter.variable}>
      <body>
      <Navbar/>
      <FloatingNav navItems={navItems}/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
